### ISSUE TITLE
Unable to access the application

### ISSUE THREAD

**Issue by manish-in-java** [hdiv/hdiv-spring-mvc-showcase#6]
Using Oracle JDK 1.8.0 patch 112 and Maven 3.2.2, the application starts up fine. However, accessing the home page throws the following exception:

    org.apache.jasper.JasperException: Unable to compile class for JSP: 

    An error occurred at line: 1 in the generated java file
    The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files

Refreshing the page changes the exception to:

    org.apache.jasper.JasperException: org.apache.jasper.JasperException: Unable to load class for JSP

**Comment by manish-in-java** [comment]
This seems to be due to Tomcat 6 not being aware of specific enhancements introduced with Java 8. See [this JDK bug](https://bugs.openjdk.java.net/browse/JDK-8155223) for details. The solution seems to be to upgrade to Tomcat 7+, which I have confirmed works.

**Comment by anderruiz** [comment]
Yes, as far as I know, Tomcat 6 is not JDK8 ready, so I guess the problem is not related with the showcase itself. Let us know if you have any other problem.

**Comment by manish-in-java** [comment]
@anderruiz, I am not sure I understood your question. Are you suggesting that the showcase should support Java 8 (and onwards)? If not, your statement `I guess the problem is not related with the showcase` is inaccurate since the instructions provided with the showcase don't work with Java 8 and onwards.

If there is no intention to support Java 8 and further, it will be better to mention it clearly on the project home page. If there is intention to support Java 8, upgrading Tomcat dependency in the POM would suffice. Either way, I think there is a clear next step for the project team.

**Comment by anderruiz** [comment]
I think that the latest commit solves this issue
